name: Upload iOS App to App Store

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 合并文件片段
    - name: Merge IPA parts
      run: |
        cat ipa/aichatgenie.ipa.part* > ipa/aichatgenie.ipa

    # 验证文件完整性
    - name: Verify file integrity
      run: |
        EXPECTED_MD5="cf5ed8fbb9b1a8b508b051459e9258d2"
        ACTUAL_MD5=$(md5 -q ipa/aichatgenie.ipa)
        
        if [ "$EXPECTED_MD5" != "$ACTUAL_MD5" ]; then
          echo "IPA file integrity check failed"
          exit 1
        fi

    # 上传到 App Store
    - name: Upload to App Store using altool
      env:
        IPA_PATH: "ipa/aichatgenie.ipa"
        APPLE_ID: "happym1224@163.com"
        APP_SPECIFIC_PASSWORD: "twss-wqfs-vboc-esng"
      run: |
        xcrun altool --upload-app -f "$IPA_PATH" \
          -t ios \
          -u "$APPLE_ID" \
          -p "$APP_SPECIFIC_PASSWORD" \
          --verbose

